language: ruby
sudo: required
dist: bionic
group: beta
cache: bundler
bundler_args: --without profile

notifications:
  irc: "irc.freenode.org#axlsx"
  email:
    recipients:
      - noel@peden.biz
    on_success: always

# Use the pre-installed Ruby versions listed at
# https://docs.travis-ci.com/user/reference/bionic/#ruby-support
matrix:
  include:
    - rvm: 2.3.8
    - rvm: 2.4.5
    - rvm: 2.5.3
    - rvm: 2.6.3
    - rvm: rbx-3
    - rvm: jruby-19mode
    - rvm: jruby-9.1.17.0
    - rvm: jruby-9.2.8.0    
    - rvm: ruby-head
    - rvm: jruby-head
  allow_failures:
    - rvm: rbx-3
    - rvm: ruby-head
    - rvm: jruby-9.1.17.0
    - rvm: jruby-9.2.8.0
    - rvm: jruby-head
jdk:
  - openjdk8
env:
  global:
    - JRUBY_OPTS="-Xcli.debug=true --debug"

# https://github.com/jruby/jruby/wiki/FAQs#why-is-jruby-so-slow-to-install-via-rvm
# https://docs.travis-ci.com/user/installing-dependencies#Installing-Packages-with-the-APT-Addon
addons:
  apt:
    packages:
    - haveged
