language: ruby
sudo: required
dist: bionic
group: edge
cache: bundler
bundler_args: --without profile

notifications:
  irc: "irc.freenode.org#axlsx"
  email:
    recipients:
      - noel@peden.biz
    on_success: always

matrix:
  include:
    - rvm: 2.3.8
    - rvm: 2.4.10
    - rvm: 2.5.8
    - rvm: 2.6.6
    - rvm: 2.7.1
    - rvm: 3.0.0
    - rvm: jruby-19mode
    - rvm: jruby-9.1.17.0
    - rvm: jruby-9.2.16.0
    - rvm: ruby-head
    - rvm: jruby-head
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.17.0
    - rvm: jruby-9.2.16.0
    - rvm: jruby-head

env:
  global:
    - JRUBY_OPTS="-Xcli.debug=true --debug"

# https://github.com/jruby/jruby/wiki/FAQs#why-is-jruby-so-slow-to-install-via-rvm
